[package]
name = "deep-into-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
affinity = "0.1.2"
rayon = "1.10.0"
threadpool = "1.8.1"
scoped-thread-pool = "1.0.4"
poolite = "0.7.1"